FROM alpine:3.12.1

RUN apk update && apk upgrade && apk add \
    openrc --no-cache \
    nginx

RUN mkdir -p /run/nginx /www

RUN adduser -D -g 'www' www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig

COPY ./srcs/index.html /www/
COPY ./srcs/nginx.conf /etc/nginx/

ENTRYPOINT ["nginx", "-g", "daemon off;"]