FROM alpine:3.12.1

RUN apk update && apk upgrade && apk add \
    openrc --no-cache \
    nginx \
    php7 \
    php7-fpm \
    php7-iconv \
    php7-json \
    php7-mbstring \
    php7-mysqli \
    php7-phar \
    php7-session

RUN wget https://wordpress.org/latest.zip -O wordpress.zip &&\
    unzip wordpress.zip &&\
    rm -rf wordpress.zip
# https://www.cyberciti.biz/faq/how-to-install-php-7-fpm-on-alpine-linux/
RUN rc-update add php-fpm7 default

RUN mkdir -p /run/nginx /wwW

RUN adduser -D -g 'www' www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

# RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig

COPY ./srcs/index.html /www/
COPY ./srcs/nginx.conf /etc/nginx/conf.d
COPY ./srcs/wp-config.php /wordpress/

RUN mkdir -p /usr/share/webapps/ && cd /usr/share/webapps && wget http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-5.0.2-all-languages.tar.gz && tar zxvf phpMyAdmin-5.0.2-all-languages.tar.gz && rm phpMyAdmin-5.0.2-all-languages.tar.gz && mv phpMyAdmin-5.0.2-all-languages phpmyadmin

RUN chmod -R 777 /usr/share/webapps/
RUN ln -s /usr/share/webapps/phpmyadmin/ /www/

COPY ./srcs/start.sh /


# RUN ["/start.sh"]
ENTRYPOINT ["/start.sh"]


# ENTRYPOINT ["nginx", "-g", "daemon off;"]