FROM alpine:3.12.1

# INSTALL PACKAGES
RUN apk update && apk upgrade && apk add \
    openrc --no-cache \
    nginx \
    php7 \
    php7-fpm \
    php7-iconv \
    php7-json \
    php7-mbstring \
    php7-mysqli \
    php7-phar \
    php7-session



RUN mkdir -p /run/nginx /www

RUN adduser -D -g 'www' www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

# RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orig

# COPY FILES
COPY ./srcs/index.html /www/
COPY ./srcs/nginx.conf /etc/nginx/conf.d

RUN mkdir -p /usr/share/webapps/ && cd /usr/share/webapps && wget http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-5.0.2-all-languages.tar.gz && tar zxvf phpMyAdmin-5.0.2-all-languages.tar.gz && rm phpMyAdmin-5.0.2-all-languages.tar.gz && mv phpMyAdmin-5.0.2-all-languages phpmyadmin

RUN chmod -R 777 /usr/share/webapps/
RUN ln -s /usr/share/webapps/phpmyadmin/ /www/

COPY ./srcs/start.sh /

# USER
RUN adduser -D -g 'Simon Fiers' ssimon
RUN echo "ssimon:secret" | chpasswd
RUN touch /home/ssimon/test.txt

# RUN ["/start.sh"]
ENTRYPOINT ["/start.sh"]


# ENTRYPOINT ["nginx", "-g", "daemon off;"]